### PR TITLE
Introduced additional Camera tests and changed CameraComms

### PR DESCRIPTION
**Pull request by GerritRo**
# Motivation

My implementation of camera tests is in a state now where I am comfortable with opening a pull-request, mainly to enable some discussion about some of the issues and talk about changes to my code.

# What is implemented?

This pull-request introduces some additional test for camera system connected to the mainboard. Compared to the previous version, it does not only check simple register r/w operations, but also tests most of the implemented camera functions for their intended function, checks image transfer and more.. The tests are implemented as followed:

- CameraComms:
  - Checks r/w to specified registers for camera and image sensor
  - Checks all image capture modes via returned file size
  - Checks r/w for gain and exposure time functions by sending N random values in accepted range
  - Checks transfer speed for a full size image and transfer success.
- CameraDarknoise:
  - Takes N images at single specified exposure time and gain setting.
  - Checks pixel distribution behaviour (mean, deviation, 99pct)
  - Checks pixel behaviour for normality
- CameraLinearity
  - Checks if mean image value scales linear with exposure time
- CameraGain
  - Checks if mean image value scales exponential with gain

A camera test set is implemented which runs a basic test suite for one camera.

# What is still missing for full functionality?

- Some tests run longer than 180s, these currently time out.
- Images are currently saved in the **working directory**. This is not optimal, and the possibility of uploading images to the Database might be beneficial.
- Graphical implementations for Darknoise distributions, Linearity and Gain fit would be useful.
- How to separate cameras into test-sets (by camera or by d-egg)

### CODE REVIEW

**Comment by jimbraun** [comment]
> Some tests run longer than 180s, these currently time out.

Can these tests be shortened?  180s is, in my view, a reasonable upper limit on a STF-like test.  I imagine this affects tests that take multiple images, e.g. CameraLinearity.  Could this test be done by using a smaller cropping mode?

> Images are currently saved in the working directory. This is not optimal, and the possibility of uploading images to the Database might be beneficial.

This needs to happen.  @csburreson can probably help with this

> Graphical implementations for Darknoise distributions, Linearity and Gain fit would be useful.

The STF database pages can plot any data you provide, but again, you just need to get in touch with @csburreson

> How to separate cameras into test-sets (by camera or by d-egg)

This should be done by camera, not by DEgg, since we also have mDOMs and individual camera testing (edited)

**Comment by jimbraun** [comment]
Also, in 0x1F I added an Iceboot function to test the SPI interface to any given camera using a large volume of data.  It would be easy to design a comms test around this function.

**Comment by GerritRo** [comment]
> Can these tests be shortened? 180s is, in my view, a reasonable upper limit on a STF-like test. I imagine this affects tests that take multiple images, e.g. CameraLinearity. Could this test be done by using a smaller cropping mode?

Okay, most of these test are currently configured so that they take less than 180 s time, just the Darknoise test gets barely above it. It puts a soft limit on the amount of images able to captured for one Darknoise test though. Changing image size or increasing transfers speeds might both be solutions to consider.

> This should be done by camera, not by DEgg, since we also have mDOMs and individual camera testing (edited)

I will implement test sets on a per camera base then.

> Also, in 0x1F I added an Iceboot function to test the SPI interface to any given camera using a large volume of data. It would be easy to design a comms test around this function.

This sounds like a valuable addition!

**Comment by jimbraun** [comment]
Today I'll add a Python wrapper that can call the Iceboot camera SPI test.

On the Darknoise test, I guess I can see how that test could need more time, since you just need to read as many pixel values as possible.  Comms bandwidth is limited by the mini-FieldHub, so there is no good opportunity to globally decrease the image transfer time.  I'd definitely be open to increasing the default timeout if the test really requires more time.

**Comment by jimbraun** [comment]
One final thought on the darknoise test: We could potentially have a function that produces a histogram of pixel values, then just transmit the histogram instead of the full image.

**Comment by jimbraun** [comment]
I've added the Python 'testCameraSPI' function that will work with Iceboot 0x1F or later.  Basically:

session.testCameraSPI(1, 100)

will write 0xAA and 0x55 to the camera test register 100 times and return the number of times the correct values were read back.  Basically:

trials = 10000
if session.testCameraSPI(1, trials) != trials:
  # ERROR!!!!!

**Comment by GerritRo** [comment]
> One final thought on the darknoise test: We could potentially have a function that produces a histogram of pixel values, then just transmit the histogram instead of the full image.

This would be a very useful feature in ice as well. Some form of onboard averaging of images would save a lot of transfer time and reduces the amount of data to be stored drastically.

**Comment by GerritRo** [comment]
# Final pre-review update:

I have added several features and QoL improvements over the last few commits, and I have arrived at a point where all further development runs into conflict with some limitation of the framework or needs external aid.

**These features are still missing:**
- Linear plots in verical for CameraGain and CameraLinearity as well as histograms for CameraDarknoise
- Find way to specify local save-folder (via command line or using the json results folder)
- A way to specify the tested camera via command line instead of hard-coding the config.json

**Comment by jweber-ice** [comment]
Add 3 plots from https://docs.google.com/presentation/d/1SQScoX_cdaudoy_SMR03wOnBZezg50AZbMNOtdRF4nE/edit#slide=id.g742e4ce525_0_0 to VeriCal

**Pull request merged**
